rules:
  - id: javascript.express.security.audit.express-check-csurf-middleware-usage.express-check-csurf-middleware-usage
    message: "CSRF middleware is intentionally not required for this stateless API."
    languages: [javascript]
    severity: INFO
    pattern: $X
    enabled: false
